package model

// Availability, execution identity, and invocation/visual observations live here.
// Instrument declarations and executable criterion semantics do not.

import (
	"encoding/json"
	"fmt"
	"path"
	"time"
)

// Availability keeps absence separate from observed zero, false, or an empty set.
// U07 evaluates it, U10 captures it, and U12 refuses inferences it cannot support.
type Availability[T any] struct {
	State  AvailabilityState `json:"state"`
	Value  *T                `json:"value,omitempty"`
	Reason string            `json:"reason,omitempty"`
}

type AvailabilityState string

const (
	Known   AvailabilityState = "known"
	Unknown AvailabilityState = "unknown"
)

func (a Availability[T]) validate(p string) error {
	switch a.State {
	case Known:
		if a.Value == nil || a.Reason != "" {
			return invalid(p, "known requires a value and no reason")
		}
	case Unknown:
		if a.Value != nil || Blank(a.Reason) {
			return invalid(p, "unknown requires a reason and no value")
		}
	default:
		return invalid(p+".state", "expected known or unknown")
	}
	return nil
}

// ExecutionIdentity is captured by U10 and compared by U07/U12. MachineID is a
// persisted generated ID, never a guessed hostname. Dirty source needs content pins.
type ExecutionIdentity struct {
	Project    ProjectID             `json:"project"`
	MachineID  Availability[ID]      `json:"machine_id"`
	SourceRefs []ArtifactRef         `json:"source_refs"`
	Head       Availability[GitHead] `json:"head"`
	Dirty      Availability[bool]    `json:"dirty"`
}
type GitHead struct {
	ObjectFormat string `json:"object_format"`
	Commit       string `json:"commit"`
}

func (h GitHead) validate(p string) error { return validateCommit(h.ObjectFormat, h.Commit, p) }
func (s ExecutionIdentity) validate(p string) error {
	if s.Dirty.State == Known && s.Dirty.Value != nil && *s.Dirty.Value {
		found := false
		for _, r := range s.SourceRefs {
			if r.Content != nil {
				found = true
			}
		}
		if !found {
			return invalid(p+".source_refs", "dirty execution requires captured source content")
		}
	}
	return nil
}

// InvocationEnvelope is generated by U10, consumed for observation/trust by
// U06/U07/U12, and displayed by U13. Each observed field carries its own availability.
// CriterionRef can honestly be unknown for measurements outside the executable vocabulary.
type InvocationEnvelope struct {
	InvocationID            ID                                            `json:"invocation_id"`
	AttemptID               ID                                            `json:"attempt_id"`
	InstrumentRef           RecordRef                                     `json:"instrument_ref"`
	CriterionRef            Availability[CriterionRef]                    `json:"criterion_ref"`
	ExecutionSourceIdentity ExecutionIdentity                             `json:"execution_source_identity"`
	Argv                    []string                                      `json:"argv"`
	InputRefs               []ArtifactRef                                 `json:"input_refs"`
	ConfigRequested         map[string]Scalar                             `json:"config_requested"`
	ConfigEffective         Availability[map[string]Availability[Scalar]] `json:"config_effective"`
	ConditionsDeclared      map[string]Scalar                             `json:"conditions_declared"`
	ConditionsObserved      Availability[map[string]Availability[Scalar]] `json:"conditions_observed"`
	Isolation               Availability[Isolation]                       `json:"isolation"`
	StartedAt               time.Time                                     `json:"started_at"`
	ObservedAt              Availability[time.Time]                       `json:"observed_at"`
	Outcome                 Availability[ProcessOutcome]                  `json:"outcome"`
	Outputs                 Availability[[]RunOutput]                     `json:"outputs"`
	Visual                  Availability[VisualObservation]               `json:"visual"`
}

// RunOutput is one file a run produced. Its identity is the invocation whose
// envelope lists it, its name inside that run, and its bytes (digest, length,
// media type). Where a copy is stored is not part of it: the configured
// artifact store finds the bytes by digest, so moving or renaming that store
// changes nothing a recorded run means. A criterion selector binds to Name.
type RunOutput struct {
	Name      string `json:"name"`
	SHA256    Digest `json:"sha256"`
	Length    uint64 `json:"length"`
	MediaType string `json:"media_type"`
}

// Ref is the output's bytes as an artifact reference: a content pin with no
// locator, since the store finds the bytes by digest and a name inside a run
// is not a path anywhere. Whatever cites or disposes of artifacts sees a run
// output through it.
func (o RunOutput) Ref() ArtifactRef {
	return ArtifactRef{Kind: "content", Selector: Selector{Kind: "whole"},
		Content: &ContentPin{SHA256: o.SHA256, Length: o.Length, MediaType: o.MediaType, Locators: []Locator{}}}
}

func (o RunOutput) validate(p string) error {
	if err := RunOutputName(o.Name, p+".name"); err != nil {
		return err
	}
	if !ValidDigest(o.SHA256) {
		return invalid(p+".sha256", "not lowercase sha-256 hex")
	}
	if Blank(o.MediaType) {
		return invalid(p+".media_type", "empty media type")
	}
	return nil
}

// RunOutputName is the one rule for an output name, in a seal and in the
// selector that reads it: a relative path in canonical form, so no two
// spellings name one output and none leaves the run.
func RunOutputName(name, p string) error {
	if err := relativePath(name, p); err != nil {
		return err
	}
	if path.Clean(name) != name {
		return invalid(p, "an output name is a canonical relative path")
	}
	return nil
}

type Isolation string

const IsolationClean Isolation = "clean"

func (i Isolation) validate(p string) error { return oneOf(string(i), p, "clean") }

// ProcessOutcome distinguishes a known exit, a signal and failure to spawn.
// Observer death is Availability unknown, never a fabricated exit code.
type ProcessOutcome struct {
	Kind       string  `json:"kind"`
	ExitCode   *int    `json:"exit_code,omitempty"`
	Signal     *string `json:"signal,omitempty"`
	Diagnostic *string `json:"diagnostic,omitempty"`
}

func (o ProcessOutcome) validate(p string) error {
	switch o.Kind {
	case "exit":
		if o.ExitCode == nil || *o.ExitCode < 0 || o.Signal != nil || o.Diagnostic != nil {
			return invalid(p, "exit requires only a nonnegative exit code")
		}
	case "signal":
		if o.Signal == nil || Blank(*o.Signal) || o.ExitCode != nil || o.Diagnostic != nil {
			return invalid(p, "signal requires only an observed signal")
		}
	case "spawn-failed":
		if o.Diagnostic == nil || Blank(*o.Diagnostic) || o.ExitCode != nil || o.Signal != nil {
			return invalid(p, "spawn failure requires only a diagnostic")
		}
	default:
		return invalid(p+".kind", "unknown process outcome")
	}
	return nil
}

// VisualObservation keeps small observed metadata typed, and pins large transform,
// lighting and material payloads. U10 captures these facts; U07/U12 compare them.
// U13 can display missing facts without guessing a rest pose or default camera.
type VisualObservation struct {
	Framing    Availability[VisualFraming]    `json:"framing"`
	Transforms Availability[ArtifactRef]      `json:"transforms"`
	Clip       Availability[string]           `json:"clip"`
	Time       Availability[json.Number]      `json:"time"`
	Seed       Availability[string]           `json:"seed"`
	Backend    Availability[string]           `json:"backend"`
	Appearance Availability[VisualAppearance] `json:"appearance"`
	Limits     Availability[VisualLimits]     `json:"limits"`
}

// VisualFraming lets the consumer determine whether the subject was actually
// visible. ProjectedBounds pins the adapter's subject-bounds result, not an image guess.
type VisualFraming struct {
	Subject         Availability[string]      `json:"subject"`
	ProjectedBounds Availability[ArtifactRef] `json:"projected_bounds"`
	CameraPosition  Availability[Vector3]     `json:"camera_position"`
	CameraTarget    Availability[Vector3]     `json:"camera_target"`
	Projection      Availability[string]      `json:"projection"`
	Viewport        Availability[Viewport]    `json:"viewport"`
	DPR             Availability[json.Number] `json:"dpr"`
}
type Vector3 struct {
	X json.Number `json:"x"`
	Y json.Number `json:"y"`
	Z json.Number `json:"z"`
}
type Viewport struct {
	Width  uint64 `json:"width"`
	Height uint64 `json:"height"`
}

func (v Viewport) validate(p string) error {
	if v.Width == 0 || v.Height == 0 {
		return invalid(p, "observed viewport dimensions must be positive")
	}
	return nil
}
func (f VisualFraming) validate(p string) error {
	if err := observedText(f.Subject, p+".subject"); err != nil {
		return err
	}
	if err := observedText(f.Projection, p+".projection"); err != nil {
		return err
	}
	if f.DPR.State == Known && f.DPR.Value != nil {
		r, err := DecimalRat(*f.DPR.Value)
		if err != nil {
			return err
		}
		if r.Sign() <= 0 {
			return invalid(p+".dpr", "observed DPR must be positive")
		}
	}
	return nil
}

// VisualAppearance exposes every appearance factor the visual trust contract
// names, while the potentially large lights/materials/override bodies stay artifacts.
type VisualAppearance struct {
	Lights              Availability[ArtifactRef] `json:"lights"`
	Exposure            Availability[json.Number] `json:"exposure"`
	ColourSpace         Availability[string]      `json:"colour_space"`
	Materials           Availability[ArtifactRef] `json:"materials"`
	DiagnosticOverrides Availability[ArtifactRef] `json:"diagnostic_overrides"`
}

func (a VisualAppearance) validate(p string) error {
	return observedText(a.ColourSpace, p+".colour_space")
}

type VisualLimits struct {
	Occlusion        Availability[string]   `json:"occlusion"`
	UnviewedSurfaces Availability[[]string] `json:"unviewed_surfaces"`
	UntestedBackends Availability[[]string] `json:"untested_backends"`
	StillLimitations string                 `json:"still_limitations" semantic:"text"`
}

func (l VisualLimits) validate(p string) error {
	if err := observedText(l.Occlusion, p+".occlusion"); err != nil {
		return err
	}
	for _, field := range []struct {
		name  string
		value Availability[[]string]
	}{{"unviewed_surfaces", l.UnviewedSurfaces}, {"untested_backends", l.UntestedBackends}} {
		if field.value.State == Known && field.value.Value != nil {
			for i, s := range *field.value.Value {
				if Blank(s) {
					return invalid(fmt.Sprintf("%s.%s[%d]", p, field.name, i), "whitespace-only is empty")
				}
			}
		}
	}
	return nil
}
func (v VisualObservation) validate(p string) error {
	for _, field := range []struct {
		name  string
		value Availability[string]
	}{{"clip", v.Clip}, {"seed", v.Seed}, {"backend", v.Backend}} {
		if err := observedText(field.value, p+"."+field.name); err != nil {
			return err
		}
	}
	return nil
}
func observedText(v Availability[string], p string) error {
	if v.State == Known && v.Value != nil && Blank(*v.Value) {
		return invalid(p, "known observation needs nonblank text")
	}
	return nil
}

func (e InvocationEnvelope) validate(p string) error {
	if len(e.Argv) == 0 || Blank(e.Argv[0]) {
		return invalid(p+".argv", "an executable argv array is required")
	}
	if e.ObservedAt.State == Known && e.ObservedAt.Value != nil && e.ObservedAt.Value.Before(e.StartedAt) {
		return invalid(p+".observed_at", "observation precedes start")
	}
	if e.Outputs.Value != nil {
		names := map[string]bool{}
		for i, o := range *e.Outputs.Value {
			if names[o.Name] {
				return invalid(fmt.Sprintf("%s.outputs[%d].name", p, i), "two outputs of one run share a name")
			}
			names[o.Name] = true
		}
	}
	return nil
}

// ValidateInvocationConfig is used by U10/U12 once the exact instrument revision
// is available. Shape decoding cannot know another record's declared knob names.
func ValidateInvocationConfig(e InvocationEnvelope, s InstrumentSpec) error {
	if err := ValidateSchema(e); err != nil {
		return err
	}
	if err := ValidateSchema(s); err != nil {
		return err
	}
	names := map[string]bool{}
	for _, n := range s.ConfigSurface {
		names[n] = true
	}
	for n := range e.ConfigRequested {
		if !names[n] {
			return invalid("config_requested."+n, "undeclared configuration name")
		}
	}
	if e.ConfigEffective.State == Known && e.ConfigEffective.Value != nil {
		for n := range *e.ConfigEffective.Value {
			if !names[n] {
				return invalid("config_effective."+n, "undeclared configuration name")
			}
		}
		for n := range names {
			if _, ok := (*e.ConfigEffective.Value)[n]; !ok {
				return invalid("config_effective."+n, "declared knob needs a value or explicit unknown")
			}
		}
	}
	return nil
}
