package query

// The optional decision-provider seam. A provider PROPOSES candidates with the
// provider, version and thresholds that produced them; it never returns a
// status, an acceptance, a disposition or a judgment, and nothing it returns
// changes any other part of an answer. A nil provider is the normal offline
// case. Ranking logic and concrete providers do not belong in this file.

import (
	"context"
	"fmt"

	"datum/internal/model"
)

type Operation string

const (
	OperationTriage   Operation = "triage"
	OperationSpanMap  Operation = "span-map"
	OperationRetrieve Operation = "retrieve"
)

// Question is scoped to exact record refs; the provider sees nothing else.
type Question struct {
	Operation Operation         `json:"operation"`
	Refs      []model.RecordRef `json:"refs"`
}

// Candidate is a suggestion. Score is the provider's decimal text, uninterpreted.
type Candidate struct {
	Ref   model.RecordRef `json:"ref"`
	Span  string          `json:"span,omitempty"`
	Score string          `json:"score"`
}

// Proposal carries candidates plus the envelope that generated them.
type Proposal struct {
	Question     Question          `json:"question"`
	Candidates   []Candidate       `json:"candidates"`
	Provider     string            `json:"provider"`
	Version      string            `json:"version"`
	Thresholds   map[string]string `json:"thresholds"`
	Availability string            `json:"availability"` // known or UNKNOWN
	Reason       string            `json:"reason,omitempty"`
	Provenance   string            `json:"provenance"`
}

// Provider answers a question with a proposal. Implementations must be safe to
// be absent: capture and every deterministic read work without one.
type Provider interface {
	Propose(ctx context.Context, q Question) (Proposal, error)
}

const proposalProvenance = "generated by a decision provider: a proposal only, not admitted, not a judgment"

func unavailable(q Question, reason string) Proposal {
	return Proposal{Question: q, Candidates: []Candidate{}, Provider: "UNKNOWN", Version: "UNKNOWN",
		Thresholds: map[string]string{}, Availability: "UNKNOWN", Reason: reason, Provenance: proposalProvenance}
}

// propose calls p, if any, and normalises its envelope. A failing or absent
// provider is UNKNOWN availability; the read that asked still succeeds.
func propose(ctx context.Context, p Provider, q Question) Proposal {
	if q.Refs == nil {
		q.Refs = []model.RecordRef{}
	}
	if p == nil {
		return unavailable(q, "no decision provider attached; this answer is the deterministic rules alone")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	got, err := p.Propose(ctx, q)
	if err != nil {
		return unavailable(q, fmt.Sprintf("decision provider failed: %v", err))
	}
	out := Proposal{Question: q, Candidates: nonNil(got.Candidates), Provider: got.Provider, Version: got.Version,
		Thresholds: got.Thresholds, Availability: "known", Provenance: proposalProvenance}
	if out.Thresholds == nil {
		out.Thresholds = map[string]string{}
	}
	if out.Provider == "" || out.Version == "" {
		return unavailable(q, "decision provider did not identify its name and version, so its proposal cannot be attributed")
	}
	return out
}
